"""add_risk_model

Revision ID: 1c8bfb667719
Revises: 887f66c2bdc9
Create Date: 2026-06-16 10:03:24.522829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8bfb667719'
down_revision: Union[str, Sequence[str], None] = '887f66c2bdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('risk_ref', sa.String(), nullable=False),
    sa.Column('risk_discription', sa.String(), nullable=False),
    sa.Column('occurence', sa.Integer(), nullable=False),
    sa.Column('significance', sa.Integer(), nullable=False),
    sa.Column('date_identified', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('date_last_assessed', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['soqm_components.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['quality_objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risks')
    # ### end Alembic commands ###
