"""remove_objective_id_nullable

Revision ID: 373fd511b31a
Revises: 5fd49fb12584
Create Date: 2026-06-27 20:57:10.772876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373fd511b31a'
down_revision: Union[str, Sequence[str], None] = '5fd49fb12584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'objective_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'objective_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
