"""add_name_response

Revision ID: 3960dc52bcc4
Revises: 613524925b31
Create Date: 2026-06-22 15:43:44.379671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3960dc52bcc4'
down_revision: Union[str, Sequence[str], None] = '613524925b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_responses', sa.Column('response_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_responses', 'response_name')
    # ### end Alembic commands ###
