"""add_response_ref_response_model

Revision ID: 55980c496f7d
Revises: 06dd60f9512d
Create Date: 2026-06-30 00:32:07.502420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55980c496f7d'
down_revision: Union[str, Sequence[str], None] = '06dd60f9512d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_responses', sa.Column('response_ref', sa.String(), nullable=False))
    op.add_column('risk_responses', sa.Column('owner', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('risk_responses_risk_id_fkey'), 'risk_responses', type_='foreignkey')
    op.drop_constraint(op.f('risk_responses_responsible_employee_fkey'), 'risk_responses', type_='foreignkey')
    op.create_foreign_key(None, 'risk_responses', 'employees', ['owner'], ['id'])
    op.drop_column('risk_responses', 'responsible_employee')
    op.drop_column('risk_responses', 'risk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_responses', sa.Column('risk_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('risk_responses', sa.Column('responsible_employee', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'risk_responses', type_='foreignkey')
    op.create_foreign_key(op.f('risk_responses_responsible_employee_fkey'), 'risk_responses', 'users', ['responsible_employee'], ['id'])
    op.create_foreign_key(op.f('risk_responses_risk_id_fkey'), 'risk_responses', 'risks', ['risk_id'], ['id'])
    op.drop_column('risk_responses', 'owner')
    op.drop_column('risk_responses', 'response_ref')
    # ### end Alembic commands ###
