"""add_risk_response_model

Revision ID: 613524925b31
Revises: f2b7bc7caa80
Create Date: 2026-06-19 14:36:41.690245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613524925b31'
down_revision: Union[str, Sequence[str], None] = 'f2b7bc7caa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_responses',
    sa.Column('response_description', sa.String(), nullable=False),
    sa.Column('response_type', sa.String(), nullable=False),
    sa.Column('date_implementation', sa.Date(), nullable=True),
    sa.Column('date_monitored_design', sa.Date(), nullable=True),
    sa.Column('date_monitored_operating', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('responsible_employee', sa.UUID(), nullable=False),
    sa.Column('evidence_notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_employee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_responses')
    # ### end Alembic commands ###
