"""add_risk_rational_risk_model

Revision ID: 72e8b84ca9a1
Revises: b7da12a33f43
Create Date: 2026-07-14 06:22:06.227519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e8b84ca9a1'
down_revision: Union[str, Sequence[str], None] = 'b7da12a33f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('risk_rational', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'risk_rational')
    # ### end Alembic commands ###
