"""add_seq_to_objective

Revision ID: 76ae6c3c6e43
Revises: b07a83b856b4
Create Date: 2026-06-23 16:40:53.831954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ae6c3c6e43'
down_revision: Union[str, Sequence[str], None] = 'b07a83b856b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_objectives', sa.Column('objective_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_objectives', 'objective_reference')
    # ### end Alembic commands ###
