"""add_display_order_soqm_components

Revision ID: 97a8f355c25f
Revises: 794a66335509
Create Date: 2026-06-08 00:05:32.078052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a8f355c25f'
down_revision: Union[str, Sequence[str], None] = '794a66335509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soqm_components', sa.Column('display_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soqm_components', 'display_order')
    # ### end Alembic commands ###
