"""add_user_risk_relationship

Revision ID: 9a59ada2ad59
Revises: 1c8bfb667719
Create Date: 2026-06-17 16:11:04.583627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a59ada2ad59'
down_revision: Union[str, Sequence[str], None] = '1c8bfb667719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'risks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('risks', 'created_by')
    # ### end Alembic commands ###
