"""add_component_state

Revision ID: a4c9eb3d4328
Revises: 8fb447278c20
Create Date: 2026-06-12 02:39:47.694887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c9eb3d4328'
down_revision: Union[str, Sequence[str], None] = '8fb447278c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soqm_components', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soqm_components', 'status')
    # ### end Alembic commands ###
