"""add_seq_component_objective

Revision ID: b07a83b856b4
Revises: 3960dc52bcc4
Create Date: 2026-06-23 16:09:35.893446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07a83b856b4'
down_revision: Union[str, Sequence[str], None] = '3960dc52bcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_objective_seq',
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'sequence', name='uq_component_seq')
    )
    op.create_unique_constraint(None, 'soqm_components', ['display_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soqm_components', type_='unique')
    op.drop_table('component_objective_seq')
    # ### end Alembic commands ###
