"""add_current_version_to_document

Revision ID: b7da12a33f43
Revises: 391fde1d94fd
Create Date: 2026-07-11 00:04:19.798958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7da12a33f43'
down_revision: Union[str, Sequence[str], None] = '391fde1d94fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('current_version_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'current_version_id')
    # ### end Alembic commands ###
