"""add_frequency_execution_risk_response

Revision ID: c314230ff4e6
Revises: ac448da87500
Create Date: 2026-07-08 20:45:51.681926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c314230ff4e6'
down_revision: Union[str, Sequence[str], None] = 'ac448da87500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_responses', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('risk_responses', sa.Column('execution_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_responses', 'execution_type')
    op.drop_column('risk_responses', 'frequency')
    # ### end Alembic commands ###
