"""add_sequence_number_to_risk

Revision ID: d0c2fcf46bba
Revises: 72e8b84ca9a1
Create Date: 2026-07-22 08:24:39.262103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0c2fcf46bba"
down_revision: Union[str, Sequence[str], None] = "72e8b84ca9a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def parse_and_load():

    return


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("risks", sa.Column("sequence_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.add_column("risks", sa.Column("component_order", sa.Integer(), nullable=True))

    risk_table = sa.table(
        "risks",
        sa.column("risk_ref", sa.String),
        sa.column("sequence_number", sa.Integer),
        sa.column("component_order", sa.Integer),
    )

    op.execute(
        risk_table.update().values(
            sequence_number=sa.cast(
                sa.func.split_part(risk_table.c.risk_ref, ".", 2), sa.Integer
            ),
            component_order=sa.cast(
                sa.func.split_part(risk_table.c.risk_ref, ".", 1),
                sa.Integer,
            ),
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risks", "sequence_number")
    op.drop_column("risks", "component_order")
    # ### end Alembic commands ###
