"""add_component_to_response_model

Revision ID: d71689a82543
Revises: 55980c496f7d
Create Date: 2026-06-30 00:38:17.936135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71689a82543'
down_revision: Union[str, Sequence[str], None] = '55980c496f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_responses', sa.Column('component_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_responses', 'component_id')
    # ### end Alembic commands ###
