"""drop_objective_text

Revision ID: d8d60983aadf
Revises: 76ae6c3c6e43
Create Date: 2026-06-23 17:13:52.583919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d60983aadf'
down_revision: Union[str, Sequence[str], None] = '76ae6c3c6e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_objectives', 'objective_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_objectives', sa.Column('objective_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
