"""add_first_last_name_employee

Revision ID: f8461ae1be49
Revises: 003c98532f03
Create Date: 2026-06-28 19:58:28.587357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8461ae1be49'
down_revision: Union[str, Sequence[str], None] = '003c98532f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
